<?php

return [
  'electric_parking_door' => 'درب پارکینگ برقی',
  'balcony' => 'بالکون',
  'bts' => 'آنتن‌دهی‌ موبایل',
  'pool' => 'استخر',
  'sauna' => 'سونا',
  'jacuzzi' => 'جکوزی',
  'elevator' => 'بالابر',
  'escalator' => 'پله‌برقی',
  'alarm_system' => 'دزدگیر',
  'cctv' => 'دوربین‌مداربسته',
  'security_guard' => 'نگهبانی',
  'electric_door' => 'درب‌برقی',
  'electric_shutter' => 'کرکره‌برقی',
  'forest_view' => 'نما جنگلی',
  'beach_view' => 'نما ساحلی',
  'mountain_view' => 'نما کوه',
  'near_kindergarten' => 'نزدیک به مهدکودک',
  'near_elementary_school' => 'مدرسه ابتدایی',
  'near_middle_school' => 'مدرسه راهنمایی',
  'near_high_school' => 'مدرسه دبیرستان',
  'technical_school' => 'هنرستان',
  'vocational_school' => 'کار و دانش',
  'near_university' => 'نزدیک به دانشگاه',
  'near_health_center' => 'نزدیک به خانه بهداشت',
  'near_clinic' => 'نزدیک به درمانگاه',
  'near_hospital' => 'نزدیک به مدرسه بیمارستان',
  'near_shop' => 'نزدیک به مغازه',
  'near_hypermarket' => 'نزدیک به هایپرمارکت',
  'near_bakery' => 'نزدیک به نانوایی',
  'near_bank' => 'نزدیک به بانک',
  'near_repair_shop' => 'نزدیک به تعمیرگاه',
  'near_oil_change' => 'نزدیک به تعویض روغنی',
  'near_car_wash' => 'نزدیک به کارواش',
];
